#!/bin/bash

MODE=$(system76-power profile | grep Profile | awk '{print $3}')

toggle() {
    if [[ $MODE == 'Balanced' ]]; then
        system76-power profile battery
        notify-send --urgency=normal "Power Saver" "Power saving mode has been turned on!" -i power-profile-power-saver-symbolic
    else
        system76-power profile balanced
        light -S 80
        notify-send --urgency=normal "Power Saver" "Power saving mode has been turned off!" -i power-profile-balanced-symbolic
    fi
}

status() {
    if [[ $MODE == 'Balanced' ]]; then
        echo "Off"
    else
        echo "On"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--mode" ]]; then
    echo $MODE
elif [[ $1 == "--status" ]]; then
    status
fi
