#!/bin/sh
if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
then
  eww update bluetooth_visible=false
  echo ""
else
  if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]
  then 
    eww update bluetooth_visible=true
    echo ""
  else
    eww update bluetooth_visible=true
    echo ""
  fi
fi