#!/bin/bash

PID=$(lsof /dev/snd/pcm*c | wc -c)

if [[ $PID -eq 0 ]]
then
  eww update mic_visible=false
  echo ""
else
  eww update mic_visible=true
  if [[ $(pamixer --default-source --get-mute) == "true" ]]; then
    echo ""
  else
    echo ""
  fi
fi