#!/usr/bin/env bash
STATUS=$(nmcli | grep wlp4s0 | awk 'FNR==1' | awk '{print $2}')
SSID=$(iwgetid | awk -F '"' '{ print $2 }')
STRENGTH=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)

toggle() {
    if [[ $STATUS == "connected" ]]; then
        nmcli radio wifi off
        notify-send --icon=window-close --urgency=normal "Wi-Fi" "Wi-Fi has been turned off!"
    else
        nmcli radio wifi on
        notify-send --icon=checkmark --urgency=normal "Wi-Fi" "Wi-Fi has been turned on, you are back online!"
    fi
}

icon() {
    if [[ "$STRENGTH" -ge "75" ]]; then
        echo ""
    elif [[ "$STRENGTH" -ge "50" ]]; then
        echo ""
    elif [[ "$STRENGTH" -ge "25" ]]; then
        echo ""
    elif [[ "$STRENGTH" -ge "0" ]]; then
        echo ""
    else
        echo ""
    fi
}

status() {
    if [[ $STATUS == "connected" ]]; then
        echo "$SSID"
    else
        echo Disconnected
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
