#!/bin/bash

if [[ $1 == "--image" ]]; then
    FILE=$HOME/.face
    if [[ -f "$FILE" ]]; then
        echo "../../.face"
    else
        echo "System-Menu/images/profile.png"
    fi
fi

if [[ $1 == "--name" ]]; then
    name=$(getent passwd `whoami` | cut -d ":" -f 5 | cut -d "," -f 1 | tr -d "\n")
    if [[ $name == "" ]]; then
        whoami
    else
        echo "$name"
    fi
fi