#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Fullscreen terminal

alacritty --class 'Fullscreen,Fullscreen' -o window.startup_mode=fullscreen window.padding.x=45 window.padding.y=45 window.opacity=1.0 font.size=12 --command cava