#!/bin/bash

while true;
do
	inactiu=$(xprintidle)
	if [ $inactiu -gt 15000 ]
	then
		eww -c $HOME/.config/eww/Lock close-all 
                xset dpms force off
                eww -c $HOME/.config/eww/Powermenu close-all
	fi
	if [ $inactiu -lt 10000 ]
	then
		eww -c $HOME/.config/eww/Lock/ open-many player-spotify lock-weather battery-lock volume-slider-lock
                eww -c $HOME/.config/eww/Powermenu close-all
	fi
	sleep 5
done
#while true;
#do
#inactiu=$(xprintidle)
#	if [ $inactiu -lt 2000 ]
#	then
#		$HOME/.scripts/eww open-many player-spotify weather calendari &
#	fi
#	sleep 1
#done
