#!/bin/bash

PID=$(lsof -e /run/user/1000/gvfs /dev/snd/pcm*c | wc -c)

if [[ $PID -eq 0 ]]
then
  echo ""
else
  if [[ $(pamixer --default-source --get-mute) == "true" ]]; then
    echo ""
  else
    echo ""
  fi
fi
